version: '3'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - 6379:6379

  redis-insight:
    container_name: redis-insight
    image: redislabs/redisinsight
    ports:
      - 5540:5540